[package]
name = "wedpr_ffi_java_fisco_bcos_sdk"
version = "0.1.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"
license = "Apache-2.0"
description = "Library of WeDPR specific utilities for FISCO BCOS Java Sdk."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ffi_fisco_bcos_sdk"
crate-type = [ "cdylib", "staticlib" ]

[dependencies]
jni = "0.13.0"
wedpr_ffi_common = { version = "1.1.0" }
wedpr_ffi_macros = "1.1.0"
wedpr_third_party_fisco_bcos_java_sdk = { path = "../../../third_party/fisco_bcos_java_sdk" }
