[package]
name = "wedpr_ffi_macros"
version = "1.0.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"
license = "Apache-2.0"
description = "Library of WeDPR ffi shared macros."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
