[package]
name = "ffi_wasm_ecc_edwards25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ffi_wasm_ecc_edwards25519"
crate-type = ["rlib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
ecc_edwards25519 = { path = "../../../crypto/ecc/ecc_edwards25519" }
