[package]
name = "wedpr_ffi_java_crypto"
version = "0.0.1"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["wedpr_f_base64", "wedpr_f_ecies_secp256k1", "wedpr_f_signature_secp256k1", "wedpr_f_hash_keccak256", "wedpr_f_signature_sm2", "wedpr_f_hash_sm3", "wedpr_f_vrf_curve25519"]
wedpr_f_base64 = [ "wedpr_ffi_common_base64" ]
wedpr_f_hex = [ "wedpr_ffi_common_hex" ]
wedpr_f_ecies_secp256k1 = [ "wedpr_l_crypto_ecies_secp256k1" ]
wedpr_f_signature_secp256k1 = [ "wedpr_l_crypto_signature_secp256k1" ]
wedpr_f_hash_keccak256 = [ "wedpr_l_crypto_hash_keccak256" ]
wedpr_f_signature_sm2 = [ "wedpr_l_crypto_signature_sm2" ]
wedpr_f_hash_sm3 = [ "wedpr_l_crypto_hash_sm3" ]
wedpr_f_vrf_curve25519 = [ "wedpr_l_crypto_vrf_curve25519" ]

[lib]
name = "ffi_java_crypto"
crate-type = [ "cdylib", "staticlib" ]

[dependencies]
jni = "0.13.0"
lazy_static = "1.4.0"
wedpr_ffi_common_base64 = { package = "wedpr_ffi_common", version = "0.0.1", features = [ "wedpr_f_base64" ], default-features = false, optional = true }
wedpr_ffi_common_hex = { package = "wedpr_ffi_common", version = "0.0.1", features = [ "wedpr_f_hex" ], default-features = false, optional = true }
wedpr_ffi_macros =  "0.0.1"
wedpr_l_crypto_vrf_curve25519 = { version = "0.0.1", optional = true }
wedpr_l_crypto_ecies_secp256k1 = { version = "0.0.1", optional = true }
wedpr_l_crypto_hash_keccak256 = { version = "0.0.1", optional = true }
wedpr_l_crypto_hash_sm3 = { version = "0.0.1", optional = true }
wedpr_l_crypto_signature_secp256k1 = { path = "../../../crypto/signature/secp256k1", optional = true }
#wedpr_l_crypto_signature_secp256k1 = { version = "0.0.1", optional = true }
wedpr_l_crypto_signature_sm2 = {path = "../../../crypto/signature/sm2", optional = true }
wedpr_l_macros = "0.0.1"
wedpr_l_utils = "0.0.1"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.13.1", default-features = false }
openssl-sys = { version = "0.9.55", features = [ "vendored" ] }
