[package]
name = "ffi_c_crypto_binary"
version = "1.0.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["wedpr_f_ecies_secp256k1", "wedpr_f_signature_secp256k1", "wedpr_f_hash_keccak256", "wedpr_f_signature_sm2", "wedpr_f_hash_sm3", "wedpr_f_vrf_curve25519"]
wedpr_f_ecies_secp256k1 = [ "wedpr_l_crypto_ecies_secp256k1" ]
wedpr_f_signature_secp256k1 = [ "wedpr_l_crypto_signature_secp256k1" ]
wedpr_f_hash_keccak256 = [ "wedpr_l_crypto_hash_keccak256" ]
wedpr_f_signature_sm2 = [ "wedpr_l_crypto_signature_sm2" ]
wedpr_f_hash_sm3 = [ "wedpr_l_crypto_hash_sm3" ]
wedpr_f_vrf_curve25519 = [ "wedpr_l_crypto_vrf_curve25519" ]

[lib]
name = "ffi_c_crypto"
crate-type = [ "cdylib", "staticlib" ]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.60"
protobuf = "2.20.0"
wedpr_ffi_c_common = "1.0.0"
wedpr_ffi_common= { path = "../../ffi_common/" }
wedpr_ffi_macros =  { path = "../../ffi_macros/" }
wedpr_l_crypto_vrf_curve25519 = { version = "1.0.0", optional = true }
wedpr_l_crypto_ecies_secp256k1 = { version = "1.0.0", optional = true }
wedpr_l_crypto_hash_keccak256 = { version = "1.0.0", optional = true }
wedpr_l_crypto_hash_sm3 = { version = "1.0.0", optional = true }
wedpr_l_crypto_signature_secp256k1 = { path = "../../../crypto/signature/secp256k1/", optional = true }
wedpr_l_crypto_signature_sm2 = { path = "../../../crypto/signature/sm2/", optional = true }
wedpr_l_protos = "1.0.0"
wedpr_l_macros = "1.0.0"
wedpr_l_utils = "1.0.0"
# This is required to generate C/C++ header files.
[build-dependencies]
cbindgen = "0.9.0"
