[package]
name = "wedpr_ffi_java_crypto_binary"
version = "1.0.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["wedpr_f_ecies_secp256k1", "wedpr_f_signature_secp256k1", "wedpr_f_hash_keccak256", "wedpr_f_signature_sm2", "wedpr_f_hash_sm3", "wedpr_f_vrf_curve25519"]
wedpr_f_ecies_secp256k1 = [ "wedpr_l_crypto_ecies_secp256k1" ]
wedpr_f_signature_secp256k1 = [ "wedpr_l_crypto_signature_secp256k1" ]
wedpr_f_hash_keccak256 = [ "wedpr_l_crypto_hash_keccak256" ]
wedpr_f_signature_sm2 = [ "wedpr_l_crypto_signature_sm2" ]
wedpr_f_hash_sm3 = [ "wedpr_l_crypto_hash_sm3" ]
wedpr_f_vrf_curve25519 = [ "wedpr_l_crypto_vrf_curve25519" ]

[lib]
name = "ffi_java_crypto_binary"
crate-type = [ "cdylib", "staticlib" ]

[dependencies]
jni = "0.13.0"
lazy_static = "1.4.0"
wedpr_ffi_macros =  { path = "../../ffi_macros/" }
wedpr_l_crypto_vrf_curve25519 = { version = "1.0.0", optional = true }
wedpr_l_crypto_ecies_secp256k1 = { version = "1.0.0", optional = true }
wedpr_l_crypto_hash_keccak256 = { version = "1.0.0", optional = true }
wedpr_l_crypto_hash_sm3 = { version = "1.0.0", optional = true }
wedpr_l_crypto_signature_secp256k1 = { path = "../../../crypto/signature/secp256k1", optional = true }
wedpr_l_crypto_signature_sm2 = { version = "1.0.1", optional = true }
wedpr_l_macros = "1.0.0"
wedpr_l_utils = "1.0.0"
wedpr_ffi_common= { path = "../../ffi_common/" }


[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.13.1", default-features = false }
openssl-sys = { version = "0.9.55", features = [ "vendored" ] }
