[package]
name = "wedpr_ffi_c_fisco"
version = "1.0.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ffi_c_fisco"
crate-type = [ "cdylib", "staticlib" ]

[dependencies]
libc = "0.2.60"
wedpr_ffi_common= { path = "../../ffi_common/" }
wedpr_ffi_macros =  { path = "../../ffi_macros/" }
wedpr_ffi_c_common = "1.0.0"
wedpr_l_macros = "1.0.0"
wedpr_l_utils = { path = "/Users/asher/WeDPR/WeDPR-Lab-Crypto/common/utils/"}
wedpr_third_party_fisco_bcos = { path = "../../../third_party/fisco_bcos/" }

