name: Rust

on: [push]

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Nightly default
        run: rustup default nightly
      - name: Build
        run: cargo build --verbose
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Calculating code coverage
        run: |
          cargo test --verbose
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash)