name: Default-Test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Nightly default
        run: rustup default nightly
#      - name: Generate proto
#        run: cd protos && cargo run && cd ../
      - name: Build
        run: cargo build --all --all-targets --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run bench
        run: cargo bench

